version: "3.8"

networks:
  traderepublic:
    driver: bridge
  node-network:
    driver: bridge

services:
#  rabbitmq:
#    image: "rabbitmq:3.7-management-alpine"
#    container_name: rabbitmq
#    volumes:
#      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json
#    ports:
#        - "5672:5672"
#        - "15672:15672"
#    networks:
#      - traderepublic
#
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 5s
#      timeout: 20s
#      retries: 5


  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  dbdata6:
